// Local embeddings using FastEmbed server
const FASTEMBED_URL = process.env.FASTEMBED_URL || 'http://localhost:8001';

export interface LocalEmbedResult {
  embedding: number[];
  timingMs: number;
  model: string;
  dimension: number;
}

export async function embedLocally(text: string): Promise<LocalEmbedResult> {
  const startTime = performance.now();

  try {
    const response = await fetch(`${FASTEMBED_URL}/embed`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        text: text,
        model: 'jinaai/jina-embeddings-v2-base-en',
      }),
    });

    if (!response.ok) {
      throw new Error(`FastEmbed server error: ${response.statusText}`);
    }

    const data = await response.json();
    const endTime = performance.now();

    return {
      embedding: data.embedding,
      timingMs: data.timingMs, // Use server-side timing for embedding only
      model: data.model,
      dimension: data.dimension,
    };
  } catch (error) {
    console.error('FastEmbed server not available:', error);
    throw new Error('FastEmbed server is not running. Start it with: ./start_fastembed.sh');
  }
}

// BM25 sparse embeddings (used only in hybrid mode)
export async function generateBM25Sparse(text: string): Promise<{ timingMs: number; model: string; sparse?: any }> {
  const startTime = performance.now();

  // BM25 is generated by Qdrant at search time
  // This is a placeholder - actual BM25 happens in Qdrant

  const endTime = performance.now();

  return {
    timingMs: Math.round(endTime - startTime),
    model: 'bm25-qdrant',
  };
}
